/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mdriver */

#ifndef _Included_mdriver
#define _Included_mdriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mdriver
 * Method:    Move
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_mdriver_Move
  (JNIEnv *, jclass, jint, jint, jint);
JNIEXPORT void JNICALL Java_mdriver_Movedmm
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
